// Auto-generated by sync-posts.ps1
// Last updated: 2026-06-04 21:01:11

const POST_STATUS = {
  "iami-kakogawa": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true,
    "2026-07": true,
    "2026-08": true,
    "2026-09": true,
    "2026-10": true,
    "2026-11": true,
    "2026-12": true
  },
  "kamada-dental": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true,
    "2026-07": true,
    "2026-08": true,
    "2026-09": true,
    "2026-10": true,
    "2026-11": true,
    "2026-12": true
  },
  "meet-dental": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true,
    "2026-07": true,
    "2026-08": true,
    "2026-09": true,
    "2026-10": true,
    "2026-11": true,
    "2026-12": true
  },
  "sapporo-occlusion": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true,
    "2026-07": true,
    "2026-08": true,
    "2026-09": true,
    "2026-10": true,
    "2026-11": true,
    "2026-12": true
  },
  "jetproduce": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true,
    "2026-07": true,
    "2026-08": true,
    "2026-09": true,
    "2026-10": true,
    "2026-11": true,
    "2026-12": true
  },
  "eiwa-juku-kita": {
    "2026-05": true,
    "2026-06": true,
    "2026-07": true,
    "2026-08": true
  },
  "eiwa-juku-minami": {
    "2026-05": true,
    "2026-06": true,
    "2026-07": true,
    "2026-08": true
  },
  "sakakibara-tax": {
    "2026-02": true,
    "2026-03": true,
    "2026-05": true,
    "2026-06": true,
    "2026-07": true,
    "2026-08": true,
    "2026-09": true,
    "2026-10": true,
    "2026-11": true,
    "2026-12": true
  },
  "shibamoto-legal": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true,
    "2026-07": true,
    "2026-08": true,
    "2026-09": true,
    "2026-10": true,
    "2026-11": true,
    "2026-12": true
  },
};

const REPORT_STATUS = {
  "iami-kakogawa": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true
  },
  "kamada-dental": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true
  },
  "meet-dental": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true
  },
  "sapporo-occlusion": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true
  },
  "jetproduce": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true
  },
  "eiwa-juku-kita": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true
  },
  "eiwa-juku-minami": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true
  },
  "sakakibara-tax": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true
  },
  "shibamoto-legal": {
    "2026-04": true,
    "2026-05": true,
    "2026-06": true
  },
};