param()
$clientsDir = "C:\Users\hangy\.gemini\antigravity\.agent\clients"
$outputFile = Join-Path $PSScriptRoot "post-status.js"

$clients = @(
    "iami-kakogawa","kamada-dental","meet-dental","sapporo-occlusion",
    "jetproduce","eiwa-juku","sakakibara-tax","shibamoto-legal"
)

function Scan-MonthFiles($baseDir, $pattern, $regex) {
    $entries = @()
    if (Test-Path $baseDir) {
        $files = Get-ChildItem -Path $baseDir -Filter $pattern -File
        foreach ($f in $files) {
            if ($f.Name -match $regex) {
                $entries += "    `"$($Matches[1])`": true"
            }
        }
    }
    return $entries
}

$now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$lines = @()
$lines += "// Auto-generated by sync-posts.ps1"
$lines += "// Last updated: $now"
$lines += ""

# POST_STATUS
$lines += "const POST_STATUS = {"
foreach ($c in $clients) {
    $dir = Join-Path $clientsDir "$c\posts"
    $entries = Scan-MonthFiles $dir "*_posts.md" '^(\d{4}-\d{2})_posts\.md$'
    if ($entries.Count -gt 0) {
        $lines += "  `"$c`": {"
        $lines += ($entries -join ",`n")
        $lines += "  },"
    } else {
        $lines += "  `"$c`": {},"
    }
}
$lines += "};"
$lines += ""

# REPORT_STATUS
$lines += "const REPORT_STATUS = {"
foreach ($c in $clients) {
    $dir = Join-Path $clientsDir "$c\reports"
    $entries = Scan-MonthFiles $dir "*_report.md" '^(\d{4}-\d{2})_report\.md$'
    if ($entries.Count -gt 0) {
        $lines += "  `"$c`": {"
        $lines += ($entries -join ",`n")
        $lines += "  },"
    } else {
        $lines += "  `"$c`": {},"
    }
}
$lines += "};"

[System.IO.File]::WriteAllText($outputFile, ($lines -join "`r`n"), [System.Text.Encoding]::UTF8)
Write-Host "Generated: $outputFile"
