plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\hangy\\.gemini\\antigravity\\scratch\\survey-app\\namba-dental"
publishOrigin = "default"
base = "C:\\Users\\hangy\\.gemini\\antigravity\\scratch\\survey-app\\namba-dental"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]