functionsDirectory = "C:\\Users\\hangy\\.gemini\\antigravity\\scratch\\survey-app\\eiwa-juku\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\hangy\\.gemini\\antigravity\\scratch\\survey-app\\eiwa-juku"
publishOrigin = "default"
base = "C:\\Users\\hangy\\.gemini\\antigravity\\scratch\\survey-app\\eiwa-juku"
functions = "C:\\Users\\hangy\\.gemini\\antigravity\\scratch\\survey-app\\eiwa-juku\\netlify\\functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]