const fs = require('fs');
const crypto = require('crypto');
const SPREADSHEET_ID='1hpKYD_DHreNBNzGKrjCHYU3rrkPTINcAaVOJKuC9IAY';
const CREDENTIALS_PATH='C:/Users/hangy/.gemini/antigravity/scratch/form_automation/google_credentials.json';
function base64url(input){return Buffer.from(input).toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');}
async function token(){const c=JSON.parse(fs.readFileSync(CREDENTIALS_PATH,'utf8')); const now=Math.floor(Date.now()/1000); const header={alg:'RS256',typ:'JWT'}; const claim={iss:c.client_email,scope:'https://www.googleapis.com/auth/spreadsheets.readonly',aud:'https://oauth2.googleapis.com/token',exp:now+3600,iat:now}; const si=`${base64url(JSON.stringify(header))}.${base64url(JSON.stringify(claim))}`; const sig=crypto.sign('RSA-SHA256',Buffer.from(si),c.private_key); const res=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:`${si}.${base64url(sig)}`})}); const d=await res.json(); if(!res.ok) throw new Error(JSON.stringify(d)); return d.access_token;}
async function main(){const t=await token(); const url=`https://sheets.googleapis.com/v4/spreadsheets/${SPREADSHEET_ID}?includeGridData=true&ranges=${encodeURIComponent("'シート1'!A1:I2000")}&fields=properties.title,sheets(properties(title,sheetId),conditionalFormats,bandedRanges,data(rowData(values(userEnteredFormat.backgroundColor,userEnteredFormat.backgroundColorStyle,effectiveFormat.backgroundColor,effectiveFormat.backgroundColorStyle,userEnteredValue))))`; const res=await fetch(url,{headers:{Authorization:`Bearer ${t}`}}); const d=await res.json(); if(!res.ok) throw new Error(JSON.stringify(d)); const s=d.sheets[0]; console.log(JSON.stringify({title:d.properties.title,sheet:s.properties.title,conditionalFormats:s.conditionalFormats||[],bandedRanges:s.bandedRanges||[]},null,2)); const rows=s.data?.[0]?.rowData||[]; for (const r of [1925,1926,1955,1994]) { const vals=rows[r-1]?.values||[]; console.log('ROW',r); for (const c of [4,5]) { console.log(c===4?'E':'F', JSON.stringify(vals[c]?.effectiveFormat?.backgroundColorStyle || vals[c]?.effectiveFormat?.backgroundColor || vals[c]?.userEnteredFormat?.backgroundColorStyle || vals[c]?.userEnteredFormat?.backgroundColor || null)); } }
}
main().catch(e=>{console.error(e);process.exit(1)});
