const fs=require('fs'); const crypto=require('crypto');
const SPREADSHEET_ID='1hpKYD_DHreNBNzGKrjCHYU3rrkPTINcAaVOJKuC9IAY';
const CREDENTIALS_PATH='C:/Users/hangy/.gemini/antigravity/scratch/form_automation/google_credentials.json';
function base64url(input){return Buffer.from(input).toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');}
async function token(){const c=JSON.parse(fs.readFileSync(CREDENTIALS_PATH,'utf8')); const now=Math.floor(Date.now()/1000); const header={alg:'RS256',typ:'JWT'}; const claim={iss:c.client_email,scope:'https://www.googleapis.com/auth/spreadsheets.readonly',aud:'https://oauth2.googleapis.com/token',exp:now+3600,iat:now}; const si=`${base64url(JSON.stringify(header))}.${base64url(JSON.stringify(claim))}`; const sig=crypto.sign('RSA-SHA256',Buffer.from(si),c.private_key); const res=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:`${si}.${base64url(sig)}`})}); const d=await res.json(); if(!res.ok)throw new Error(JSON.stringify(d)); return d.access_token;}
function q(s){return `'${s.replace(/'/g,"''")}'`;}
function same(v){return (v||'').trim();}
async function main(){const t=await token(); const range=encodeURIComponent(`${q('シート1')}!A:O`); const res=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${SPREADSHEET_ID}/values/${range}`,{headers:{Authorization:`Bearer ${t}`}}); const d=await res.json(); if(!res.ok)throw new Error(JSON.stringify(d)); const rows=d.values||[]; for (const rn of [631,655]) { const row=rows[rn-1]||[]; const vals={C:same(row[2]),E:same(row[4]),F:same(row[5])}; const matches={}; for (const [col,val] of Object.entries(vals)) { matches[col]=val ? rows.map((r,i)=>({row:i+1, company:r[2]||'', E:r[4]||'', F:r[5]||'', val:same(col==='C'?r[2]:col==='E'?r[4]:r[5])})).filter(x=>x.row!==1 && x.val===val).map(x=>({row:x.row, company:x.company, E:x.E, F:x.F})) : []; } console.log(JSON.stringify({row:rn, values:vals, matchCounts:{C:matches.C.length,E:matches.E.length,F:matches.F.length}, matches},null,2)); }}
main().catch(e=>{console.error(e);process.exit(1)});
