const fs = require('fs');
const crypto = require('crypto');
const SPREADSHEET_ID='1hpKYD_DHreNBNzGKrjCHYU3rrkPTINcAaVOJKuC9IAY';
const CREDENTIALS_PATH='C:/Users/hangy/.gemini/antigravity/scratch/form_automation/google_credentials.json';
function base64url(input){return Buffer.from(input).toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');}
async function token(){const c=JSON.parse(fs.readFileSync(CREDENTIALS_PATH,'utf8')); const now=Math.floor(Date.now()/1000); const header={alg:'RS256',typ:'JWT'}; const claim={iss:c.client_email,scope:'https://www.googleapis.com/auth/spreadsheets.readonly',aud:'https://oauth2.googleapis.com/token',exp:now+3600,iat:now}; const si=`${base64url(JSON.stringify(header))}.${base64url(JSON.stringify(claim))}`; const sig=crypto.sign('RSA-SHA256',Buffer.from(si),c.private_key); const res=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:`${si}.${base64url(sig)}`})}); const d=await res.json(); if(!res.ok) throw new Error(JSON.stringify(d)); return d.access_token;}
function q(s){return `'${s.replace(/'/g,"''")}'`;}
async function main(){const t=await token(); const range=encodeURIComponent(`${q('シート1')}!A:O`); const res=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${SPREADSHEET_ID}/values/${range}`,{headers:{Authorization:`Bearer ${t}`}}); const d=await res.json(); if(!res.ok) throw new Error(JSON.stringify(d)); const rows=d.values||[]; function stats(col){const m=new Map(); rows.slice(1).forEach((r,i)=>{const v=(r[col]||'').trim(); if(!v)return; if(!m.has(v))m.set(v,[]); m.get(v).push(i+2);}); const dup=[...m.entries()].filter(([,a])=>a.length>1).sort((a,b)=>b[1].length-a[1].length); return {uniqueDupValues:dup.length, rowsInDupGroups:dup.reduce((s,[,a])=>s+a.length,0), top:dup.slice(0,10).map(([v,a])=>({value:v,count:a.length,rows:a.slice(0,10)}))};} console.log(JSON.stringify({rows:rows.length, C_company:stats(2), E_url:stats(4), F_form:stats(5)},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
