// categories.js — generated by generate-data.ps1 (ASCII-safe, no Japanese)
// Edit labels/icons here and re-run generate-data.ps1 to update dashboard

const CATEGORIES = [
  { id: "all",          label: "\u3059\u3079\u3066",           icon: "\u26a1",  color: "#a78bfa" },
  { id: "system",       label: "\u30b7\u30b9\u30c6\u30e0\u30fb\u30c4\u30fc\u30eb",  icon: "\uD83D\uDEE0\uFE0F",  color: "#60a5fa" },
  { id: "report",       label: "\u30ec\u30dd\u30fc\u30c8\u30fb\u65e5\u6b21",   icon: "\uD83D\uDCCB",  color: "#34d399" },
  { id: "content",      label: "SNS\u30fb\u30b3\u30f3\u30c6\u30f3\u30c4",  icon: "\uD83D\uDCF1",  color: "#f472b6" },
  { id: "web",          label: "Web\u5236\u4f5c\u30fb\u305d\u306e\u4ed6", icon: "\uD83C\uDF10",  color: "#fb923c" },
  { id: "research",     label: "\u30ea\u30b5\u30fc\u30c1",       icon: "\uD83D\uDD0D",  color: "#fbbf24" },
  { id: "gbp-core",     label: "GBP\u57fa\u76e4",          icon: "\uD83D\uDCCA",  color: "#4ade80" },
  { id: "gbp-post",     label: "GBP\u6295\u7a3f\u696d\u7a2e\u5225",   icon: "\u270D\uFE0F",  color: "#a78bfa" },
  { id: "gbp-industry", label: "GBP\u696d\u7a2e\u5225\u904b\u7528",   icon: "\uD83C\uDFEA",  color: "#38bdf8" },
];
