# generate-data.ps1
# SKILL.md をスキャンして skills-data.js を再生成するスクリプト
# 使い方: .\generate-data.ps1

$skillsDir = "c:\Users\hangy\.gemini\antigravity\.agent\skills"
$outputFile = "$PSScriptRoot\skills-data.js"

# カテゴリマッピング（フォルダ名 → カテゴリID）
$categoryMap = @{
  "skill-management"              = "system"
  "chat-ng-learner"               = "system"
  "anticrow"                      = "system"
  "git-backup"                    = "system"
  "company-search"                = "system"
  "company-search-quality-check"  = "system"
  "form-automation"               = "system"
  "contact-auto"                  = "system"
  "ops-pdca"                      = "system"
  "idea-inbox"                    = "system"
  "daily-report"                  = "report"
  "daily-report-quality-check"    = "report"
  "sns"                           = "content"
  "content-strategy"              = "content"
  "blog-title-research"           = "content"
  "blog-writing"                  = "content"
  "blog-writing-qa"               = "content"
  "website-production"            = "web"
  "coconala-listing"              = "web"
  "great-presenter"               = "web"
  "small-company-research"        = "research"
  "gbp-partner-research"          = "research"
  "gbp-meo-core"                  = "gbp-core"
  "gbp-diagnostic"                = "gbp-core"
  "gbp-meo-post-core"             = "gbp-core"
  "gbp-report-quality-check"      = "gbp-core"
  "gbp-meo-post-dental-occlusion" = "gbp-post"
  "gbp-meo-post-dental-preventive"= "gbp-post"
  "gbp-meo-post-jetproduce"       = "gbp-post"
  "gbp-meo-beauty"                = "gbp-industry"
  "gbp-meo-bodywork"              = "gbp-industry"
  "gbp-meo-education"             = "gbp-industry"
  "gbp-meo-legal"                 = "gbp-industry"
  "gbp-meo-medical"               = "gbp-industry"
  "gbp-meo-real-estate"           = "gbp-industry"
  "gbp-meo-restaurant"            = "gbp-industry"
  "gbp-meo-retail"                = "gbp-industry"
  "gbp-meo-service"               = "gbp-industry"
}

$skills = Get-ChildItem $skillsDir -Recurse -Filter "SKILL.md" |
  Where-Object { $_.FullName -notmatch "gbp-diagnostic\\.agent" } |
  ForEach-Object {
    $lines = Get-Content $_.FullName -Encoding UTF8
    $folder = $_.Directory.Name
    $lastWrite = $_.LastWriteTime.ToString("yyyy-MM-ddTHH:mm:ss")

    $nameLine = $lines | Select-String -Pattern '^name:\s*' | Select-Object -First 1
    $descLine = $lines | Select-String -Pattern '^description:\s*' | Select-Object -First 1

    $name = if ($nameLine) { ($nameLine.Line -replace '^name:\s*','').Trim() } else { $folder }
    $desc = if ($descLine) { ($descLine.Line -replace '^description:\s*','').Trim() } else { "" }

    # JSON escape
    $name = $name -replace '"','\"'
    $desc = $desc -replace '"','\"'

    $cat = if ($categoryMap.ContainsKey($folder)) { $categoryMap[$folder] } else { "system" }

    "  {`n    id: `"$folder`",`n    name: `"$name`",`n    folder: `"$folder`",`n    category: `"$cat`",`n    description: `"$desc`",`n    lastModified: `"$lastWrite`",`n    tags: []`n  }"
  }

$js = "// Auto-generated by generate-data.ps1`n// $(Get-Date -Format 'yyyy-MM-dd HH:mm')`n`nconst SKILLS_DATA = [`n" + ($skills -join ",`n") + "`n];"

$js | Out-File -FilePath $outputFile -Encoding UTF8 -NoNewline
Write-Host "✅ $($skills.Count) スキルを $outputFile に書き出しました" -ForegroundColor Green
