// Auto-generated by generate-data.ps1
// 2026-08-28 10:59:03

const SKILLS_DATA = [
  {
    id: "000-pipeline-run",
    name: "pipeline-run",
    folder: "000-pipeline-run",
    category: "system",
    description: "営業フォーム自動化の4スキル（①リスト収集→②問い合わせURL抽出→③冒頭文生成→④フォーム送信）を、1つのGoogleシートに対して順に回す指揮者。シートの埋まり具合を見て開始工程を自動判定し、既定は全自動で回す（依頼が曖昧なときだけ計画を確認）。「営業して」「このシートで営業を回して」「リストから送信まで全部やって」「営業パイプラインを回して」で起動する。",
    command: null,
    lastModified: "2026-07-27T11:16:16",
    tags: []
  },
  {
    id: "001-list-extract",
    name: "list-extract",
    folder: "001-list-extract",
    category: "system",
    description: "Googleマップ/ローカル検索や求人媒体からWeb制作・Webマーケ会社などの事業者を収集し、統一CSV（company_name, url, address, phone, maps_url）を新規生成する。求人媒体からは「今 求人を出している（現在募集中の）会社」を自社採用ページ経由で集められる。「事業者リストを集めて」「Googleマップから会社を収集」「営業リストを作って」「求人を出している会社を集めて」「採用中の会社をリストにして」で起動する。",
    command: null,
    lastModified: "2026-07-27T11:16:16",
    tags: []
  },
  {
    id: "002-contact-extract",
    name: "contact-extract",
    folder: "002-contact-extract",
    category: "system",
    description: "企業リスト（CSV または Googleスプレッドシート）の各社HP（url列）から問い合わせページURLを抽出・正規化し、contact_url列を足す。「シートのURLを問い合わせページのリンクに変換して」「スプレッドシートの会社の問い合わせフォームURLを埋めて」「問い合わせURLを抽出」「各社の問い合わせページを探して」「contact_urlを埋めて」で起動する。",
    command: null,
    lastModified: "2026-07-27T11:16:16",
    tags: []
  },
  {
    id: "003-opener-generate",
    name: "opener-generate",
    folder: "003-opener-generate",
    category: "system",
    description: "企業リストCSVの各社HPを読み、その会社に合わせた営業フォーム用の「冒頭文」をAI生成して message 列を作る。冒頭文以降は共通文を自動連結。「冒頭文を作って」「各社向けの営業文を生成」「会社ごとにパーソナライズして」で起動する。",
    command: null,
    lastModified: "2026-07-27T11:16:16",
    tags: []
  },
  {
    id: "004-template-fill",
    name: "template-fill",
    folder: "004-template-fill",
    category: "system",
    description: "会社名だけを変数にした固定のテンプレ営業文を、指定シートの company_name 列から社名を差し込んで message 列を作る。AIなし・HP不要の決定論的な文字置換で速い・安い・文面はユーザーが完全管理。「テンプレ営業文を差し込んで」「社名だけ差し替えて営業文を量産」「固定文で営業文を作って」「用意した営業文の宛名だけ差し替えて」で起動する。",
    command: null,
    lastModified: "2026-07-27T11:16:16",
    tags: []
  },
  {
    id: "005-form-send",
    name: "autoform-send",
    folder: "005-form-send",
    category: "system",
    description: "ローカル CSV から日本企業のお問い合わせフォームへ営業メッセージを自動送信する。HTTP POST 先行 + 営業禁止/Bot 保護早期スキップ + 汎用フォーム パターンマッチング (Stage 1.5) + Pareto noAI フィルタ + AI fallback のハイブリッド動作。「フォーム営業をやる」「問い合わせ自動送信したい」「企業リストにメッセージを送りたい」と言われたら起動する。",
    command: null,
    lastModified: "2026-08-24T10:38:20",
    tags: []
  },
  {
    id: "006-result-review",
    name: "result-review",
    folder: "006-result-review",
    category: "system",
    description: "④form-sendの結果CSVを集計し、ユーザーが入力するファネル指標（送信母数/資料リンク閲覧率/返信数/面談数/契約数）と突き合わせて「どの段が落ちているか」を診断し、③冒頭文/文面を中心とした改善アクションを提案する。「営業結果を振り返って」「送信結果から改善案を出して」「今回のランを分析して」「振り返りレポートを作って」で起動する。",
    command: null,
    lastModified: "2026-07-27T11:16:16",
    tags: []
  },
  {
    id: "007-schedule-setup",
    name: "schedule-setup",
    folder: "007-schedule-setup",
    category: "system",
    description: "営業パイプラインを各自のPCで「指示なし定期実行」できるよう登録・変更・解除する。リスト取り(①②③)は毎日・送信(④)はユーザー指定時刻で別枠。Mac(launchd)/Windows(Task Scheduler)をOS自動判定。時刻や頻度はヒアリングで決め、後から変更可。「毎朝自動でリスト取りして」「営業を定期実行にして」「スケジュール登録して」「実行時刻を変えたい」「自動化を止めて」で起動する。",
    command: null,
    lastModified: "2026-08-05T13:36:31",
    tags: []
  },
  {
    id: "antigravity",
    name: "gbp-review-reply",
    folder: "antigravity",
    category: "system",
    description: "GBP口コミへの返信案を自動生成するスキル。星評価別×5トーンで複数案を出力。SEOキーワードを自然に含め、MEOランキング向上に貢献。/gbp-review-reply で起動。",
    command: null,
    lastModified: "2026-07-03T09:46:49",
    tags: []
  },
  {
    id: "blog-title-research",
    name: "blog-title-research",
    folder: "blog-title-research",
    category: "content",
    description: "ジェットプロデュース（jet-produce.com）のコラム記事タイトルをリサーチ・設計するスキル。「タイトル考えて」「記事タイトル決めて」「KW調べて」等の依頼時に必ず使う。悩み抽出→KW調査→競合分析→AI検索（AI Overviews・AIモード）確認→タイトル生成の5ステップで、SEO・CTR・AI検索を踏まえた王道/差別化/フィルター書き換えの3パターンを出力する。公開後のCTRリライトにも対応。/blog-title-research で起動。",
    command: null,
    lastModified: "2026-07-03T22:59:28",
    tags: []
  },
  {
    id: "blog-writing",
    name: "blog-writing",
    folder: "blog-writing",
    category: "content",
    description: "ジェットプロデュース（jet-produce.com）のコラムブログ記事を執筆するスキル。店舗・クリニック・士業向けSEO/AI検索最適化記事を生成。音声文字起こしを素材化する前工程にも対応。SERP分析→ブリーフ(17項目)→PREP/PAS/AIDA構成→執筆（反論処理・CTA設計込み）→QAゲートまで一貫対応。/blog-writing で起動。",
    command: null,
    lastModified: "2026-07-25T09:32:46",
    tags: []
  },
  {
    id: "blog-writing-qa",
    name: "blog-writing-qa",
    folder: "blog-writing-qa",
    category: "content",
    description: "ジェットプロデュース（jet-produce.com）のブログ記事を、ユーザーへの報告前に品質検査するスキル。8軸（各100点・数学的整合済み）で採点し、合否と改善指示を出力。形式だけでなく検索意図充足・事実性・反論処理も検査。/blog-writing-qa で起動。",
    command: null,
    lastModified: "2026-07-03T23:05:39",
    tags: []
  },
  {
    id: "chat-ng-learner",
    name: "chat-ng-learner",
    folder: "chat-ng-learner",
    category: "system",
    description: "チャットでの指摘や品質エラー（NG）をリアルタイムで検知し、絶対にすり抜けや再発を起こさないための最上位ルールレジストリへ強制記録させるメタスキル。",
    command: null,
    lastModified: "2026-05-01T14:46:33",
    tags: []
  },
  {
    id: "client-chat-review",
    name: "client-chat-review",
    folder: "client-chat-review",
    category: "system",
    description: "クライアント・見込み客・代理店・取引先への返信下書きを貼るだけで、相手目線で辛口壁打ちするスキル。返信下書きの貼り付けや「添削して」「これ送っていい？」「辛口で見て」で必ず使うこと。デフォルトは即レス添削（判定1行→指摘最大3つ→修正版1つ）で、「採点して」「フルで」と言われた時だけ8軸採点+送信可否判定のフルモードを実行する。ユーザーの好み・NG表現・再発指摘は台帳に1行ずつ蓄積して育てる。新規フォーム営業の提案文検査は対象外。",
    command: null,
    lastModified: "2026-07-25T09:32:40",
    tags: []
  },
  {
    id: "coconala-listing",
    name: "coconala-listing",
    folder: "coconala-listing",
    category: "web",
    description: "ococona라出品文の作成・改善スキル。出品画面スクショで確認した公式仕様・Proマーケター視点での構成設計・NGパターンを定義。/coconala-listing で起動。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "coconala-listing",
    name: "coconala-listing",
    folder: "coconala-listing",
    category: "web",
    description: "ココナラ出品文（サービスタイトル・キャッチコピー・サービス内容・購入にあたってのお願い・有料オプション・Q&A）の新規作成・改善スキル。「ココナラ」「出品文」「出品ページ」「タイトル考えて」「出品を改善して」等の依頼時に必ず使うこと。出品画面スクショで確認した公式文字数制限を厳守し、タイトル×キャッチコピーのキーワード分散設計と、全項目の文字数検証表つきで納品する。/coconala-listing で起動。",
    command: null,
    lastModified: "2026-07-17T21:34:20",
    tags: []
  },
  {
    id: "codex",
    name: "instagram-content-pro",
    folder: "codex",
    category: "system",
    description: "Instagramのアカウント戦略・訴求設計・プロフィール導線・月間運用・投稿企画・投稿文・ハッシュタグ・リール台本・カルーセル構成・アカウント分析・インサイト分析・PDCA更新を行う。ユーザーが「Instagram投稿」「インスタ投稿作って」「インスタ運用」「プロフィール改善」「プロフィール導線」「訴求設計」「月間カレンダー」「リール作って」「リール台本」「カルーセル」「投稿文」「ハッシュタグ」「投稿改善」「アカウント分析」「インサイト分析」「スキル更新して」と依頼したら必ず使う。",
    command: null,
    lastModified: "2026-07-10T17:01:04",
    tags: []
  },
  {
    id: "codex",
    name: "gbp-review-reply",
    folder: "codex",
    category: "system",
    description: "Googleビジネスプロフィールの口コミ返信文を日本語で作る。口コミ返信、Googleレビュー返信、GBP返信、低評価対応、星だけレビューへの返答を依頼されたら必ず使い、公開返信案、調整意図、投稿前確認を出す。",
    command: null,
    lastModified: "2026-07-03T09:46:49",
    tags: []
  },
  {
    id: "company-search",
    name: "company_search",
    folder: "company-search",
    category: "system",
    description: "Web検索で企業情報を自動収集し、Google Sheetsに書き込む営業リスト作成ツール。3段階フォールバック検索、企業HPクロール、重複/除外フィルタリング、品質チェック必須報告機能を搭載。ローカルマスターキャッシュ方式による高速重複ブロック対応。書き込み後は必ず company-search-quality-check スキルの全５軸チェックを実行する。設計思想：「悪い企業を後から弾く（ネガティブ）」ではなく「良い企業である証拠を先に確認する（ポジティブ）」。",
    command: null,
    lastModified: "2026-07-05T21:53:33",
    tags: []
  },
  {
    id: "company-search-quality-check",
    name: "企業リスト品質チェックスキル",
    folder: "company-search-quality-check",
    category: "system",
    description: "企業リスト（Google Sheets）の品質を、これまで発生した全是正事例をMECEに網羅した独立チェックスキル。company-searchスキルで収集したデータの「書き込み後」に必ず実行する。人名・見出し語・ノイズテキストの混入、誤フォームNG判定、大手企業混入、URLと企業名の乖離 の4軸を完全カバー。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "contact-form-assist",
    name: "contact-form-assist",
    folder: "contact-form-assist",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-07-17T19:03:55",
    tags: []
  },
  {
    id: "content-strategy",
    name: "content-strategy",
    folder: "content-strategy",
    category: "content",
    description: "ジェットプロデュース（jet-produce.com）のブログコンテンツを中長期で計画・運用するための戦略スキル。ピラー・クラスター構造管理、編集カレンダー、KPI設計（3Tier）、季節テーマ、PDCAフロー。/content-strategy で起動。",
    command: null,
    lastModified: "2026-05-03T05:18:34",
    tags: []
  },
  {
    id: "daily-report",
    name: "daily-report",
    folder: "daily-report",
    category: "report",
    description: ">-",
    command: null,
    lastModified: "2026-07-17T19:34:51",
    tags: []
  },
  {
    id: "daily-report-quality-check",
    name: "daily-report-quality-check",
    folder: "daily-report-quality-check",
    category: "report",
    description: "デイリーレポート完成後に実行する品質チェックスキル。全セッション網羅・INCIDENT漏れ・クライアント名正確性・重要度順序を検証する。/daily-report-quality-check で起動。",
    command: null,
    lastModified: "2026-07-17T19:36:55",
    tags: []
  },
  {
    id: "decision-record",
    name: "意思決定・構造変更の履歴記録（decision-record）",
    folder: "decision-record",
    category: "system",
    description: "構造変更・設計判断・インシデントの履歴（ADR方式）を1イベント1ファイルで記録するスキル。①スキルやファイルの廃止・移動・保存先変更などの破壊的変更、②トレードオフを伴う設計判断、③インシデント・失敗と再発防止策、のいずれかが発生したセッションでは、終了前に必ず使うこと。「履歴を残して」「記録して」「ADR残して」「決定を記録して」でも起動。.agent/history/ 配下に記録ファイルと索引（INDEX.md）の行を出力する。日常の成果物作成だけのセッション（投稿・レポート・リサーチ等）では使わない。",
    command: null,
    lastModified: "2026-07-07T15:46:09",
    tags: []
  },
  {
    id: "gbp-diagnostic",
    name: "GBP MEO診断レポート",
    folder: "gbp-diagnostic",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-07T08:02:44",
    tags: []
  },
  {
    id: "gbp-meo-core",
    name: "GBP MEO運用コアスキル",
    folder: "gbp-meo-core",
    category: "gbp-core",
    description: "GBP（Googleビジネスプロフィール）のMEO戦略立案・現状分析・改善提案を行う時に必ず使うコアスキル。「MEO対策して」「GBP改善して」「上位表示したい」「競合分析して」等の依頼、および業種別の広告規制確認が必要な投稿・返信・診断作業で参照する。戦略チェックリスト・KPI設計・業種別法規制リファレンスを提供する。投稿文の作成はgbp-meo-post-core、月次レポートはgbp-monthly-report、診断レポートはgbp-diagnosticへ委譲する。",
    command: null,
    lastModified: "2026-07-07T15:23:42",
    tags: []
  },
  {
    id: "gbp-meo-post-core",
    name: "GBP MEO投稿作成コア",
    folder: "gbp-meo-post-core",
    category: "gbp-core",
    description: "GBP投稿作成、MEO投稿、Googleビジネスプロフィール投稿、月次投稿、既存投稿改善、投稿文レビューを行う時に必ず使う。確認済み材料だけで投稿案を作り、未確認事実・口コミ風表現・季節や家庭状況・来店状況の断定を防ぎ、gbp-post-quality-checkで検査済みの投稿文を出力する。",
    command: null,
    lastModified: "2026-08-08T13:52:54",
    tags: []
  },
  {
    id: "gbp-monthly-report",
    name: "GBP月次レポート自動生成",
    folder: "gbp-monthly-report",
    category: "gbp-core",
    description: "クライアント向けGBP月次パフォーマンスレポートをNode.jsスクリプトで自動生成するスキル。Google SheetsのCSVデータを読み込み、KPI計算・競合比較・推奨アクションを含むHTML/PDFレポートを一括生成。スプレッドシート連携版（generate_report_from_sheet.js）とローカルCSV版（generate_monthly_report.js）の2モードを搭載。",
    command: null,
    lastModified: "2026-08-03T12:45:49",
    tags: []
  },
  {
    id: "gbp-partner-research",
    name: "GBPパートナー候補リサーチ コアスキル",
    folder: "gbp-partner-research",
    category: "research",
    description: "GBP/MEO運用サービスの協業パートナー候補となる業種をリサーチし、優先順位付けとキーワード設計を行うコアスキル。1000社超の集客支援実績を持つプロマーケターの視点で業種評価・キーワード設計を行い、company-searchスキルと連携して企業リスト抽出まで一気通貫で実行する。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-post-quality-check",
    name: "GBP投稿文 品質チェックスキル",
    folder: "gbp-post-quality-check",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-08-08T13:51:09",
    tags: []
  },
  {
    id: "gbp-report-quality-check",
    name: "gbp-report-quality-check",
    folder: "gbp-report-quality-check",
    category: "gbp-core",
    description: "GBP月次レポートのHTML/PDF生成物が正しいかを機械的に検査・検証する。/gbp-report-quality-check で起動。",
    command: null,
    lastModified: "2026-05-02T06:24:24",
    tags: []
  },
  {
    id: "gbp-review-analysis",
    name: "gbp-review-analysis",
    folder: "gbp-review-analysis",
    category: "gbp-core",
    description: "GBP口コミデータの全件抽出・テキスト分析・強み/弱み抽出・HTMLレポート生成スキル。GoogleマップURLを入力→Playwrightで口コミ全件取得→テーマ分類・感情分析→営業用/伴走用レポート出力。/gbp-review-analysis で起動。",
    command: null,
    lastModified: "2026-07-15T14:58:06",
    tags: []
  },
  {
    id: "gbp-review-reply",
    name: "GBP口コミ返信",
    folder: "gbp-review-reply",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-18T21:59:11",
    tags: []
  },
  {
    id: "gbp-review-reply",
    name: "GBP口コミ返信",
    folder: "gbp-review-reply",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-19T15:59:10",
    tags: []
  },
  {
    id: "gbp-review-reply",
    name: "GBP口コミ返信",
    folder: "gbp-review-reply",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-19T15:59:10",
    tags: []
  },
  {
    id: "gbp-review-reply",
    name: "GBP口コミ返信",
    folder: "gbp-review-reply",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-22T19:53:52",
    tags: []
  },
  {
    id: "gbp-review-reply",
    name: "GBP口コミ返信",
    folder: "gbp-review-reply",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-19T15:59:10",
    tags: []
  },
  {
    id: "gbp-review-reply",
    name: "GBP口コミ返信",
    folder: "gbp-review-reply",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-22T19:53:52",
    tags: []
  },
  {
    id: "gbp-review-reply",
    name: "GBP口コミ返信",
    folder: "gbp-review-reply",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-18T16:12:59",
    tags: []
  },
  {
    id: "gbp-review-reply",
    name: "GBP口コミ返信",
    folder: "gbp-review-reply",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-18T20:55:55",
    tags: []
  },
  {
    id: "gbp-review-reply",
    name: "GBP口コミ返信",
    folder: "gbp-review-reply",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-18T10:26:04",
    tags: []
  },
  {
    id: "gbp-review-reply",
    name: "GBP口コミ返信",
    folder: "gbp-review-reply",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-18T16:53:37",
    tags: []
  },
  {
    id: "git-backup",
    name: "Git バックアップスキル",
    folder: "git-backup",
    category: "system",
    description: "|",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "git-backup",
    name: "Git バックアップスキル",
    folder: "git-backup",
    category: "system",
    description: "|",
    command: null,
    lastModified: "2026-07-05T21:53:33",
    tags: []
  },
  {
    id: "great-presenter",
    name: "🎤 グレートプレゼンタースキル v2.0",
    folder: "great-presenter",
    category: "web",
    description: "プロフェッショナル・スピーチ＆プレゼンテーション総合スキル。講話の企画・台本作成・レジュメ設計・演出ポイント・添削を支援する。倫理法人会モーニングセミナー40分講話にも完全対応。/great-presenter で起動。",
    command: null,
    lastModified: "2026-05-02T06:41:53",
    tags: []
  },
  {
    id: "idea-inbox",
    name: "💡 idea-inbox スキル",
    folder: "idea-inbox",
    category: "system",
    description: ">",
    command: null,
    lastModified: "2026-05-02T09:49:08",
    tags: []
  },
  {
    id: "instagram-content-pro",
    name: "Instagram実践投稿運用",
    folder: "instagram-content-pro",
    category: "content",
    description: "Instagramのアカウント戦略・訴求設計・プロフィール導線・月間運用・投稿企画・リール台本・カルーセル構成・ハッシュタグ・アカウント分析・インサイト分析・PDCA更新を行い、戦略シート・30日カレンダー・台本・監査結果をクライアント別フォルダへ保存する。ユーザーが「インスタ運用」「プロフィール改善」「プロフィール導線」「訴求設計」「月間カレンダー」「リール作って」「リール台本」「カルーセル」「投稿改善」「アカウント分析」「インサイト分析」と依頼したら必ず使う。キャプション投稿文単体のバズ作成は sns-buzz-writer が担当のため、このスキルは使わない。",
    command: null,
    lastModified: "2026-07-10T17:22:03",
    tags: []
  },
  {
    id: "proposal-writing",
    name: "proposal-writing",
    folder: "proposal-writing",
    category: "system",
    description: "Web制作会社へ送るGoogleビジネスプロフィール運用のパートナー提案文を支援する。「提案文を作って」「1000字版と2000字版」「営業文を添削して」「A/B案」と依頼されたら必ず使うこと。第1弾はWeb制作会社向けのみで、企業調査・個社カスタマイズ・フォーム送信は行わない。",
    command: null,
    lastModified: "2026-07-25T12:37:50",
    tags: []
  },
  {
    id: "proposal-writing",
    name: "proposal-writing",
    folder: "proposal-writing",
    category: "system",
    description: "Web制作会社へ送るGoogleビジネスプロフィール運用のパートナー提案文を支援する。「提案文を作って」「1000字版と2000字版」「営業文を添削して」「A/B案」と依頼されたら必ず使うこと。第1弾はWeb制作会社向けのみで、企業調査・個社カスタマイズ・フォーム送信は行わない。",
    command: null,
    lastModified: "2026-07-25T11:00:18",
    tags: []
  },
  {
    id: "site-seo-launch",
    name: "site-seo-launch",
    folder: "site-seo-launch",
    category: "web",
    description: "WordPress/SWELLテーマで制作したサイトを本番公開する際のSEO設定スキル。SEO SIMPLE PACK設定・GA4連携（CV計測・内部除外含む）・Search Console登録・インデックスリクエスト・公開前後チェックリストを網羅。/site-seo-launch で起動。",
    command: null,
    lastModified: "2026-05-09T15:02:39",
    tags: []
  },
  {
    id: "skill",
    name: "playwright-cli",
    folder: "skill",
    category: "system",
    description: "Automate browser interactions, test web pages and work with Playwright tests.",
    command: null,
    lastModified: "2026-07-27T11:29:14",
    tags: []
  },
  {
    id: "skill",
    name: "gbp-review-reply",
    folder: "skill",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-07-18T21:59:11",
    tags: []
  },
  {
    id: "skill-checker",
    name: "Skill Checker",
    folder: "skill-checker",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-06-13T07:42:00",
    tags: []
  },
  {
    id: "skill-creator",
    name: "Skill Creator",
    folder: "skill-creator",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-06-13T07:45:14",
    tags: []
  },
  {
    id: "skill-management",
    name: "skill-management",
    folder: "skill-management",
    category: "system",
    description: "スキルの保存場所・命名規則・スキル一覧・タスク前確認(STEP 0)を定めた憲法スキル。スキルの新規作成は skill-creator、既存改善は skill-update、品質検査は skill-checker に委譲。【最重要】あらゆるタスク実行前に「現在のスキル一覧」を確認し、該当スキルがあればそのSKILL.mdを読んでから作業を開始すること。/skill-management で起動。",
    command: null,
    lastModified: "2026-07-25T11:15:21",
    tags: []
  },
  {
    id: "skill-snapshot",
    name: "sns-buzz-writer",
    folder: "skill-snapshot",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-07-10T16:46:32",
    tags: []
  },
  {
    id: "skill-snapshot",
    name: "GBP MEO診断レポート",
    folder: "skill-snapshot",
    category: "system",
    description: "GoogleマップURLを入力するだけで、見込み顧客のGBP（Googleビジネスプロフィール）を5軸×5段階で自動診断し、伸びしろTOP3・推定機会損失を含む営業用レポートを生成する。オーナーが「専門家に任せたい」と思える設計。",
    command: null,
    lastModified: "2026-07-07T07:45:18",
    tags: []
  },
  {
    id: "skill-snapshot",
    name: "gbp-meo-core",
    folder: "skill-snapshot",
    category: "system",
    description: "Googleビジネスプロフィール（GBP）のMEO対策・ローカルSEO運用を、200社以上の支援実績を持つプロマーケターの視点で体系化したコアスキル。戦略立案→実行→効果測定→改善のPDCAを業種横断で実装する。",
    command: null,
    lastModified: "2026-07-07T15:21:05",
    tags: []
  },
  {
    id: "skill-update",
    name: "Skill Update",
    folder: "skill-update",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-06-13T08:21:47",
    tags: []
  },
  {
    id: "small-company-research",
    name: "Small Company Research スキル",
    folder: "small-company-research",
    category: "research",
    description: "小規模企業の提案候補リストを作成するリサーチスキル。ポータルサイト・検索結果・比較記事から候補企業を収集し、公式サイトから企業情報を抽出、キーワード判定・重複管理・品質チェックを経てGoogle Sheets/CSVに出力する。スクレイピングファースト・トークン不使用設計。",
    command: null,
    lastModified: "2026-07-05T21:53:33",
    tags: []
  },
  {
    id: "sns-buzz-writer",
    name: "sns-buzz-writer",
    folder: "sns-buzz-writer",
    category: "content",
    description: ">-",
    command: null,
    lastModified: "2026-07-10T16:47:16",
    tags: []
  },
  {
    id: "survey-app-deploy",
    name: "survey-app-deploy",
    folder: "survey-app-deploy",
    category: "system",
    description: "|",
    command: null,
    lastModified: "2026-05-14T17:19:29",
    tags: []
  },
  {
    id: "swell-section-design",
    name: "SWELLセクションデザイン",
    folder: "swell-section-design",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-07-07T16:16:11",
    tags: []
  },
  {
    id: "trace",
    name: "playwright-trace",
    folder: "trace",
    category: "system",
    description: "Inspect Playwright trace files from the command line — list actions, view requests, console, errors, snapshots and screenshots.",
    command: null,
    lastModified: "2026-07-27T11:29:14",
    tags: []
  },
  {
    id: "transcript-knowledge-mining",
    name: "文字起こしナレッジ抽出（transcript-knowledge-mining）",
    folder: "transcript-knowledge-mining",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-06-13T12:19:37",
    tags: []
  },
  {
    id: "website-production",
    name: "🏗️ Webサイト制作スキル（本体）",
    folder: "website-production",
    category: "web",
    description: "Webサイト制作の統合スキル（本体）。最低ヒアリング、業種別設計、画像素材作成、トップページ設計・実装、品質確認、およびWordPress×SWELL受託案件の全工程（企画→デザイン→構築→公開→SEO→納品）を扱う。ユーザーが「Webサイトを作って」「ホームページ制作」「デモサイト」「サイト挿入画像」「業種別プロンプト」「LP制作」と依頼したら必ず使う。成果物は制作プロンプト、画像指示、HTML/CSS/JS、工程チェックリスト、確認結果。",
    command: null,
    lastModified: "2026-07-24T14:42:32",
    tags: []
  },
  {
    id: "website-production",
    name: "🏗️ Webサイト制作スキル（本体）",
    folder: "website-production",
    category: "web",
    description: "Webサイト制作の統合スキル（本体）。最低ヒアリング、業種別設計、画像素材作成、トップページ設計・実装、品質確認、およびWordPress×SWELL受託案件の全工程（企画→デザイン→構築→公開→SEO→納品）を扱う。ユーザーが「Webサイトを作って」「ホームページ制作」「デモサイト」「サイト挿入画像」「業種別プロンプト」「LP制作」と依頼したら必ず使う。成果物は制作プロンプト、画像指示、HTML/CSS/JS、工程チェックリスト、確認結果。",
    command: null,
    lastModified: "2026-07-06T16:05:40",
    tags: []
  },
  {
    id: "website-production",
    name: "🏗️ Webサイト制作スキル（本体）",
    folder: "website-production",
    category: "web",
    description: "Webサイト制作の統合スキル（本体）。最低ヒアリング、業種別設計、画像素材作成、トップページ設計・実装、品質確認、およびWordPress×SWELL受託案件の全工程（企画→デザイン→構築→公開→SEO→納品）を扱う。ユーザーが「Webサイトを作って」「ホームページ制作」「デモサイト」「サイト挿入画像」「業種別プロンプト」「LP制作」と依頼したら必ず使う。成果物は制作プロンプト、画像指示、HTML/CSS/JS、工程チェックリスト、確認結果。",
    command: null,
    lastModified: "2026-07-24T17:18:18",
    tags: []
  }
];

// categories.js — generated by generate-data.ps1 (ASCII-safe, no Japanese)
// Edit labels/icons here and re-run generate-data.ps1 to update dashboard

const CATEGORIES = [
  { id: "all",          label: "\u3059\u3079\u3066",           icon: "\u26a1",  color: "#a78bfa" },
  { id: "system",       label: "\u30b7\u30b9\u30c6\u30e0\u30fb\u30c4\u30fc\u30eb",  icon: "\uD83D\uDEE0\uFE0F",  color: "#60a5fa" },
  { id: "report",       label: "\u30ec\u30dd\u30fc\u30c8\u30fb\u65e5\u6b21",   icon: "\uD83D\uDCCB",  color: "#34d399" },
  { id: "content",      label: "SNS\u30fb\u30b3\u30f3\u30c6\u30f3\u30c4",  icon: "\uD83D\uDCF1",  color: "#f472b6" },
  { id: "web",          label: "Web\u5236\u4f5c\u30fb\u305d\u306e\u4ed6", icon: "\uD83C\uDF10",  color: "#fb923c" },
  { id: "research",     label: "\u30ea\u30b5\u30fc\u30c1",       icon: "\uD83D\uDD0D",  color: "#fbbf24" },
  { id: "gbp-core",     label: "GBP\u57fa\u76e4",          icon: "\uD83D\uDCCA",  color: "#4ade80" },
  { id: "gbp-post",     label: "GBP\u6295\u7a3f\u696d\u7a2e\u5225",   icon: "\u270D\uFE0F",  color: "#a78bfa" },
  { id: "gbp-industry", label: "GBP\u696d\u7a2e\u5225\u904b\u7528",   icon: "\uD83C\uDFEA",  color: "#38bdf8" },
];
