// Auto-generated by generate-data.ps1
// 2026-07-09 15:53:38

const SKILLS_DATA = [
  {
    id: "antigravity",
    name: "gbp-review-reply",
    folder: "antigravity",
    category: "system",
    description: "GBP口コミへの返信案を自動生成するスキル。星評価別×5トーンで複数案を出力。SEOキーワードを自然に含め、MEOランキング向上に貢献。/gbp-review-reply で起動。",
    command: null,
    lastModified: "2026-07-03T09:46:49",
    tags: []
  },
  {
    id: "blog-title-research",
    name: "blog-title-research",
    folder: "blog-title-research",
    category: "content",
    description: "ジェットプロデュース（jet-produce.com）のコラム記事タイトルをリサーチ・設計するスキル。「タイトル考えて」「記事タイトル決めて」「KW調べて」等の依頼時に必ず使う。悩み抽出→KW調査→競合分析→AI検索（AI Overviews・AIモード）確認→タイトル生成の5ステップで、SEO・CTR・AI検索を踏まえた王道/差別化/フィルター書き換えの3パターンを出力する。公開後のCTRリライトにも対応。/blog-title-research で起動。",
    command: null,
    lastModified: "2026-07-03T22:59:28",
    tags: []
  },
  {
    id: "blog-writing",
    name: "blog-writing",
    folder: "blog-writing",
    category: "content",
    description: "ジェットプロデュース（jet-produce.com）のコラムブログ記事を執筆するスキル。店舗・クリニック・士業向けSEO/AI検索最適化記事を生成。音声文字起こしを素材化する前工程にも対応。SERP分析→ブリーフ(17項目)→PREP/PAS/AIDA構成→執筆（反論処理・CTA設計込み）→QAゲートまで一貫対応。/blog-writing で起動。",
    command: null,
    lastModified: "2026-07-03T23:01:35",
    tags: []
  },
  {
    id: "blog-writing-qa",
    name: "blog-writing-qa",
    folder: "blog-writing-qa",
    category: "content",
    description: "ジェットプロデュース（jet-produce.com）のブログ記事を、ユーザーへの報告前に品質検査するスキル。8軸（各100点・数学的整合済み）で採点し、合否と改善指示を出力。形式だけでなく検索意図充足・事実性・反論処理も検査。/blog-writing-qa で起動。",
    command: null,
    lastModified: "2026-07-03T23:05:39",
    tags: []
  },
  {
    id: "chat-ng-learner",
    name: "chat-ng-learner",
    folder: "chat-ng-learner",
    category: "system",
    description: "チャットでの指摘や品質エラー（NG）をリアルタイムで検知し、絶対にすり抜けや再発を起こさないための最上位ルールレジストリへ強制記録させるメタスキル。",
    command: null,
    lastModified: "2026-05-01T14:46:33",
    tags: []
  },
  {
    id: "coconala-listing",
    name: "coconala-listing",
    folder: "coconala-listing",
    category: "web",
    description: "ococona라出品文の作成・改善スキル。出品画面スクショで確認した公式仕様・Proマーケター視点での構成設計・NGパターンを定義。/coconala-listing で起動。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "codex",
    name: "gbp-review-reply",
    folder: "codex",
    category: "system",
    description: "Googleビジネスプロフィールの口コミ返信文を日本語で作る。口コミ返信、Googleレビュー返信、GBP返信、低評価対応、星だけレビューへの返答を依頼されたら必ず使い、公開返信案、調整意図、投稿前確認を出す。",
    command: null,
    lastModified: "2026-07-03T09:46:49",
    tags: []
  },
  {
    id: "company-search",
    name: "company_search",
    folder: "company-search",
    category: "system",
    description: "Web検索で企業情報を自動収集し、Google Sheetsに書き込む営業リスト作成ツール。3段階フォールバック検索、企業HPクロール、重複/除外フィルタリング、品質チェック必須報告機能を搭載。ローカルマスターキャッシュ方式による高速重複ブロック対応。書き込み後は必ず company-search-quality-check スキルの全５軸チェックを実行する。設計思想：「悪い企業を後から弾く（ネガティブ）」ではなく「良い企業である証拠を先に確認する（ポジティブ）」。",
    command: null,
    lastModified: "2026-07-05T21:53:33",
    tags: []
  },
  {
    id: "company-search-quality-check",
    name: "企業リスト品質チェックスキル",
    folder: "company-search-quality-check",
    category: "system",
    description: "企業リスト（Google Sheets）の品質を、これまで発生した全是正事例をMECEに網羅した独立チェックスキル。company-searchスキルで収集したデータの「書き込み後」に必ず実行する。人名・見出し語・ノイズテキストの混入、誤フォームNG判定、大手企業混入、URLと企業名の乖離 の4軸を完全カバー。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "contact-auto",
    name: "contact-auto",
    folder: "contact-auto",
    category: "system",
    description: "企業お問ぁE��わせフォームへの自動送信スキル、EF7特化HTTP直接送信+高精度フィールド認識Playwright+マッピング不�EスキチE�EのハイブリチE��アーキチE��チャ。select/radio/checkbox完�E対応、Etags: [form, automation, sales, playwright, http, hybrid, patchright, select, radio]",
    command: null,
    lastModified: "2026-07-05T21:53:33",
    tags: []
  },
  {
    id: "content-strategy",
    name: "content-strategy",
    folder: "content-strategy",
    category: "content",
    description: "ジェットプロデュース（jet-produce.com）のブログコンテンツを中長期で計画・運用するための戦略スキル。ピラー・クラスター構造管理、編集カレンダー、KPI設計（3Tier）、季節テーマ、PDCAフロー。/content-strategy で起動。",
    command: null,
    lastModified: "2026-05-03T05:18:34",
    tags: []
  },
  {
    id: "daily-report",
    name: "daily-report",
    folder: "daily-report",
    category: "report",
    description: "【デイリーレポート作成時は必ずこのファイルを全文読んでから始めること】ファイル名はYYMMDDdaily-report.md、保存先はdaily-reports/、作成前にSTEP 0〜7を順守すること。スキルを読まずに独自フォーマットで作成することは絶対禁止。/daily-report で起動。",
    command: null,
    lastModified: "2026-07-05T21:53:33",
    tags: []
  },
  {
    id: "daily-report-quality-check",
    name: "daily-report-quality-check",
    folder: "daily-report-quality-check",
    category: "report",
    description: "デイリーレポート完成後に実行する品質チェックスキル。全セッション網羅・INCIDENT漏れ・クライアント名正確性・重要度順序を検証する。/daily-report-quality-check で起動。",
    command: null,
    lastModified: "2026-05-01T22:22:52",
    tags: []
  },
  {
    id: "decision-record",
    name: "意思決定・構造変更の履歴記録（decision-record）",
    folder: "decision-record",
    category: "system",
    description: "構造変更・設計判断・インシデントの履歴（ADR方式）を1イベント1ファイルで記録するスキル。①スキルやファイルの廃止・移動・保存先変更などの破壊的変更、②トレードオフを伴う設計判断、③インシデント・失敗と再発防止策、のいずれかが発生したセッションでは、終了前に必ず使うこと。「履歴を残して」「記録して」「ADR残して」「決定を記録して」でも起動。.agent/history/ 配下に記録ファイルと索引（INDEX.md）の行を出力する。日常の成果物作成だけのセッション（投稿・レポート・リサーチ等）では使わない。",
    command: null,
    lastModified: "2026-07-07T15:46:09",
    tags: []
  },
  {
    id: "form-automation",
    name: "📝 フォーム自動入力スキル",
    folder: "form-automation",
    category: "system",
    description: "PlaywrightベースのWebフォーム自動入力スキル。Google Sheetsから企業リストを読み込み、各社の問い合わせフォームに自動入力する（送信は人間が手動）。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-diagnostic",
    name: "GBP MEO診断レポート",
    folder: "gbp-diagnostic",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-07T08:02:44",
    tags: []
  },
  {
    id: "gbp-meo-core",
    name: "GBP MEO運用コアスキル",
    folder: "gbp-meo-core",
    category: "gbp-core",
    description: "GBP（Googleビジネスプロフィール）のMEO戦略立案・現状分析・改善提案を行う時に必ず使うコアスキル。「MEO対策して」「GBP改善して」「上位表示したい」「競合分析して」等の依頼、および業種別の広告規制確認が必要な投稿・返信・診断作業で参照する。戦略チェックリスト・KPI設計・業種別法規制リファレンスを提供する。投稿文の作成はgbp-meo-post-core、月次レポートはgbp-monthly-report、診断レポートはgbp-diagnosticへ委譲する。",
    command: null,
    lastModified: "2026-07-07T15:23:42",
    tags: []
  },
  {
    id: "gbp-meo-post-core",
    name: "GBP MEO投稿作成コア",
    folder: "gbp-meo-post-core",
    category: "gbp-core",
    description: "GBP投稿作成、MEO投稿、Googleビジネスプロフィール投稿、月次投稿、既存投稿改善、投稿文レビューを行う時に必ず使う。確認済み材料だけで投稿案を作り、未確認事実・口コミ風表現・季節や家庭状況・来店状況の断定を防ぎ、gbp-post-quality-checkで検査済みの投稿文を出力する。",
    command: null,
    lastModified: "2026-07-04T09:08:57",
    tags: []
  },
  {
    id: "gbp-monthly-report",
    name: "GBP月次レポート自動生成",
    folder: "gbp-monthly-report",
    category: "gbp-core",
    description: "クライアント向けGBP月次パフォーマンスレポートをNode.jsスクリプトで自動生成するスキル。Google SheetsのCSVデータを読み込み、KPI計算・競合比較・推奨アクションを含むHTML/PDFレポートを一括生成。スプレッドシート連携版（generate_report_from_sheet.js）とローカルCSV版（generate_monthly_report.js）の2モードを搭載。",
    command: null,
    lastModified: "2026-07-07T15:22:48",
    tags: []
  },
  {
    id: "gbp-partner-research",
    name: "GBPパートナー候補リサーチ コアスキル",
    folder: "gbp-partner-research",
    category: "research",
    description: "GBP/MEO運用サービスの協業パートナー候補となる業種をリサーチし、優先順位付けとキーワード設計を行うコアスキル。1000社超の集客支援実績を持つプロマーケターの視点で業種評価・キーワード設計を行い、company-searchスキルと連携して企業リスト抽出まで一気通貫で実行する。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-post-quality-check",
    name: "GBP投稿文 品質チェックスキル",
    folder: "gbp-post-quality-check",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-02T20:06:06",
    tags: []
  },
  {
    id: "gbp-report-quality-check",
    name: "gbp-report-quality-check",
    folder: "gbp-report-quality-check",
    category: "gbp-core",
    description: "GBP月次レポートのHTML/PDF生成物が正しいかを機械的に検査・検証する。/gbp-report-quality-check で起動。",
    command: null,
    lastModified: "2026-05-02T06:24:24",
    tags: []
  },
  {
    id: "gbp-review-analysis",
    name: "gbp-review-analysis",
    folder: "gbp-review-analysis",
    category: "gbp-core",
    description: "GBP口コミデータの全件抽出・テキスト分析・強み/弱み抽出・HTMLレポート生成スキル。GoogleマップURLを入力→Playwrightで口コミ全件取得→テーマ分類・感情分析→営業用/伴走用レポート出力。/gbp-review-analysis で起動。",
    command: null,
    lastModified: "2026-05-04T05:31:28",
    tags: []
  },
  {
    id: "gbp-review-reply",
    name: "GBP口コミ返信",
    folder: "gbp-review-reply",
    category: "gbp-core",
    description: ">-",
    command: null,
    lastModified: "2026-07-03T09:58:06",
    tags: []
  },
  {
    id: "git-backup",
    name: "Git バックアップスキル",
    folder: "git-backup",
    category: "system",
    description: "|",
    command: null,
    lastModified: "2026-07-05T21:53:33",
    tags: []
  },
  {
    id: "git-backup",
    name: "Git バックアップスキル",
    folder: "git-backup",
    category: "system",
    description: "|",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "great-presenter",
    name: "🎤 グレートプレゼンタースキル v2.0",
    folder: "great-presenter",
    category: "web",
    description: "プロフェッショナル・スピーチ＆プレゼンテーション総合スキル。講話の企画・台本作成・レジュメ設計・演出ポイント・添削を支援する。倫理法人会モーニングセミナー40分講話にも完全対応。/great-presenter で起動。",
    command: null,
    lastModified: "2026-05-02T06:41:53",
    tags: []
  },
  {
    id: "idea-inbox",
    name: "💡 idea-inbox スキル",
    folder: "idea-inbox",
    category: "system",
    description: ">",
    command: null,
    lastModified: "2026-05-02T09:49:08",
    tags: []
  },
  {
    id: "ops-pdca",
    name: "ops-pdca",
    folder: "ops-pdca",
    category: "system",
    description: "contact-auto の日次運用PDCAサイクル。「送信→集計→分析→パッチ→検証→SKILL反映」の一気通貫フローを定義。daily-report の CHECK-1/CHECK-2 と contact-auto の学習エンジンを橋渡しする。/ops-pdca で起動。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "sales-copywriting",
    name: "sales-copywriting",
    folder: "sales-copywriting",
    category: "system",
    description: "お問い合わせフォーム経由のBtoB営業提案文を「型」で量産・PDCA改善するスキル。成約はゴールではなくスタート。伴走者としての最初の握手を設計する。/sales-copywriting で起動。",
    command: null,
    lastModified: "2026-05-05T07:51:15",
    tags: []
  },
  {
    id: "sales-copywriting-qa",
    name: "sales-copywriting-qa",
    folder: "sales-copywriting-qa",
    category: "system",
    description: "sales-copywritingスキルで作成した提案文の品質を辛口で検査するスキル。型通りか、漏れがないか、誤解を生むリスクはないかを多角的にフィードバックする。/sales-copywriting-qa で起動。",
    command: null,
    lastModified: "2026-05-05T07:55:09",
    tags: []
  },
  {
    id: "site-seo-launch",
    name: "site-seo-launch",
    folder: "site-seo-launch",
    category: "web",
    description: "WordPress/SWELLテーマで制作したサイトを本番公開する際のSEO設定スキル。SEO SIMPLE PACK設定・GA4連携（CV計測・内部除外含む）・Search Console登録・インデックスリクエスト・公開前後チェックリストを網羅。/site-seo-launch で起動。",
    command: null,
    lastModified: "2026-05-09T15:02:39",
    tags: []
  },
  {
    id: "skill-checker",
    name: "Skill Checker",
    folder: "skill-checker",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-06-13T07:42:00",
    tags: []
  },
  {
    id: "skill-creator",
    name: "Skill Creator",
    folder: "skill-creator",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-06-13T07:45:14",
    tags: []
  },
  {
    id: "skill-management",
    name: "skill-management",
    folder: "skill-management",
    category: "system",
    description: "スキルの保存場所・命名規則・スキル一覧・タスク前確認(STEP 0)を定めた憲法スキル。スキルの新規作成は skill-creator、既存改善は skill-update、品質検査は skill-checker に委譲。【最重要】あらゆるタスク実行前に「現在のスキル一覧」を確認し、該当スキルがあればそのSKILL.mdを読んでから作業を開始すること。/skill-management で起動。",
    command: null,
    lastModified: "2026-07-07T16:20:46",
    tags: []
  },
  {
    id: "skill-snapshot",
    name: "GBP MEO診断レポート",
    folder: "skill-snapshot",
    category: "system",
    description: "GoogleマップURLを入力するだけで、見込み顧客のGBP（Googleビジネスプロフィール）を5軸×5段階で自動診断し、伸びしろTOP3・推定機会損失を含む営業用レポートを生成する。オーナーが「専門家に任せたい」と思える設計。",
    command: null,
    lastModified: "2026-07-07T07:45:18",
    tags: []
  },
  {
    id: "skill-snapshot",
    name: "gbp-meo-core",
    folder: "skill-snapshot",
    category: "system",
    description: "Googleビジネスプロフィール（GBP）のMEO対策・ローカルSEO運用を、200社以上の支援実績を持つプロマーケターの視点で体系化したコアスキル。戦略立案→実行→効果測定→改善のPDCAを業種横断で実装する。",
    command: null,
    lastModified: "2026-07-07T15:21:05",
    tags: []
  },
  {
    id: "skill-update",
    name: "Skill Update",
    folder: "skill-update",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-06-13T08:21:47",
    tags: []
  },
  {
    id: "small-company-research",
    name: "Small Company Research スキル",
    folder: "small-company-research",
    category: "research",
    description: "小規模企業の提案候補リストを作成するリサーチスキル。ポータルサイト・検索結果・比較記事から候補企業を収集し、公式サイトから企業情報を抽出、キーワード判定・重複管理・品質チェックを経てGoogle Sheets/CSVに出力する。スクレイピングファースト・トークン不使用設計。",
    command: null,
    lastModified: "2026-07-05T21:53:33",
    tags: []
  },
  {
    id: "survey-app-deploy",
    name: "survey-app-deploy",
    folder: "survey-app-deploy",
    category: "system",
    description: "|",
    command: null,
    lastModified: "2026-05-14T17:19:29",
    tags: []
  },
  {
    id: "swell-section-design",
    name: "SWELLセクションデザイン",
    folder: "swell-section-design",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-07-07T16:16:11",
    tags: []
  },
  {
    id: "transcript-knowledge-mining",
    name: "文字起こしナレッジ抽出（transcript-knowledge-mining）",
    folder: "transcript-knowledge-mining",
    category: "system",
    description: ">-",
    command: null,
    lastModified: "2026-06-13T12:19:37",
    tags: []
  },
  {
    id: "website-production",
    name: "🏗️ Webサイト制作スキル（本体）",
    folder: "website-production",
    category: "web",
    description: "Webサイト制作の統合スキル（本体）。最低ヒアリング、業種別設計、画像素材作成、トップページ設計・実装、品質確認、およびWordPress×SWELL受託案件の全工程（企画→デザイン→構築→公開→SEO→納品）を扱う。ユーザーが「Webサイトを作って」「ホームページ制作」「デモサイト」「サイト挿入画像」「業種別プロンプト」「LP制作」と依頼したら必ず使う。成果物は制作プロンプト、画像指示、HTML/CSS/JS、工程チェックリスト、確認結果。",
    command: null,
    lastModified: "2026-07-06T16:05:40",
    tags: []
  }
];

// categories.js — generated by generate-data.ps1 (ASCII-safe, no Japanese)
// Edit labels/icons here and re-run generate-data.ps1 to update dashboard

const CATEGORIES = [
  { id: "all",          label: "\u3059\u3079\u3066",           icon: "\u26a1",  color: "#a78bfa" },
  { id: "system",       label: "\u30b7\u30b9\u30c6\u30e0\u30fb\u30c4\u30fc\u30eb",  icon: "\uD83D\uDEE0\uFE0F",  color: "#60a5fa" },
  { id: "report",       label: "\u30ec\u30dd\u30fc\u30c8\u30fb\u65e5\u6b21",   icon: "\uD83D\uDCCB",  color: "#34d399" },
  { id: "content",      label: "SNS\u30fb\u30b3\u30f3\u30c6\u30f3\u30c4",  icon: "\uD83D\uDCF1",  color: "#f472b6" },
  { id: "web",          label: "Web\u5236\u4f5c\u30fb\u305d\u306e\u4ed6", icon: "\uD83C\uDF10",  color: "#fb923c" },
  { id: "research",     label: "\u30ea\u30b5\u30fc\u30c1",       icon: "\uD83D\uDD0D",  color: "#fbbf24" },
  { id: "gbp-core",     label: "GBP\u57fa\u76e4",          icon: "\uD83D\uDCCA",  color: "#4ade80" },
  { id: "gbp-post",     label: "GBP\u6295\u7a3f\u696d\u7a2e\u5225",   icon: "\u270D\uFE0F",  color: "#a78bfa" },
  { id: "gbp-industry", label: "GBP\u696d\u7a2e\u5225\u904b\u7528",   icon: "\uD83C\uDFEA",  color: "#38bdf8" },
];
