// Auto-generated by generate-data.ps1
// 2026-05-29 20:59:04

const SKILLS_DATA = [
  {
    id: "anticrow",
    name: "AntiCrow スキル",
    folder: "anticrow",
    category: "system",
    description: "AntiCrow 拡張機能の機能を活用するためのスキル。チームモード、連続オートモード、IPC通信、進捗報告、ファイル送信などの使い方を理解する。",
    command: null,
    lastModified: "2026-05-19T06:09:18",
    tags: []
  },
  {
    id: "blog-title-research",
    name: "blog-title-research",
    folder: "blog-title-research",
    category: "content",
    description: "ジェットプロデュース（jet-produce.com）のコラムブログ用記事タイトルをリサーチ・設計するスキル。SEO/AI検索最適化・CTR向上・競合分析・KW調査の5ステップフロー。PREP/PAS/AIDA構成に対応したタイトル案を3パターン生成。/blog-title-research で起動。",
    command: null,
    lastModified: "2026-05-03T05:17:49",
    tags: []
  },
  {
    id: "blog-writing",
    name: "blog-writing",
    folder: "blog-writing",
    category: "content",
    description: "ジェットプロデュース（jet-produce.com）のコラムブログ記事を執筆するスキル。店舗・クリニック・士業向けSEO/AI検索最適化記事を3,000〜5,000文字で生成。コンテンツブリーフ作成→PREP/PAS/AIDA構成選択→読者目線ライティング→WordPress/SWELL整形まで一貫対応。/blog-writing で起動。",
    command: null,
    lastModified: "2026-05-03T06:37:20",
    tags: []
  },
  {
    id: "blog-writing-qa",
    name: "blog-writing-qa",
    folder: "blog-writing-qa",
    category: "content",
    description: "ジェットプロデュース（jet-produce.com）のブログ記事を、ユーザーへの報告前に品質検査するスキル。SEOキーワード配置・構成フレームワーク適合・ライティング品質・法令コンプライアンス・ブランドボイス・冒頭キャッチー度を7軸で採点し、合否と改善指示を出力。/blog-writing-qa で起動。",
    command: null,
    lastModified: "2026-05-03T05:40:35",
    tags: []
  },
  {
    id: "chat-ng-learner",
    name: "chat-ng-learner",
    folder: "chat-ng-learner",
    category: "system",
    description: "チャットでの指摘や品質エラー（NG）をリアルタイムで検知し、絶対にすり抜けや再発を起こさないための最上位ルールレジストリへ強制記録させるメタスキル。",
    command: null,
    lastModified: "2026-05-01T14:46:33",
    tags: []
  },
  {
    id: "coconala-listing",
    name: "coconala-listing",
    folder: "coconala-listing",
    category: "web",
    description: "ococona라出品文の作成・改善スキル。出品画面スクショで確認した公式仕様・Proマーケター視点での構成設計・NGパターンを定義。/coconala-listing で起動。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "company-search",
    name: "company_search",
    folder: "company-search",
    category: "system",
    description: "Web検索で企業情報を自動収集し、Google Sheetsに書き込む営業リスト作成ツール。3段階フォールバック検索、企業HPクロール、重複/除外フィルタリング、品質チェック必須報告機能を搭載。ローカルマスターキャッシュ方式による高速重複ブロック対応。書き込み後は必ず company-search-quality-check スキルの全５軸チェックを実行する。設計思想：「悪い企業を後から弾く（ネガティブ）」ではなく「良い企業である証拠を先に確認する（ポジティブ）」。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "company-search-quality-check",
    name: "企業リスト品質チェックスキル",
    folder: "company-search-quality-check",
    category: "system",
    description: "企業リスト（Google Sheets）の品質を、これまで発生した全是正事例をMECEに網羅した独立チェックスキル。company-searchスキルで収集したデータの「書き込み後」に必ず実行する。人名・見出し語・ノイズテキストの混入、誤フォームNG判定、大手企業混入、URLと企業名の乖離 の4軸を完全カバー。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "contact-auto",
    name: "contact-auto",
    folder: "contact-auto",
    category: "system",
    description: "企業お問ぁE��わせフォームへの自動送信スキル、EF7特化HTTP直接送信+高精度フィールド認識Playwright+マッピング不�EスキチE�EのハイブリチE��アーキチE��チャ。select/radio/checkbox完�E対応、Etags: [form, automation, sales, playwright, http, hybrid, patchright, select, radio]",
    command: null,
    lastModified: "2026-05-06T14:50:53",
    tags: []
  },
  {
    id: "content-strategy",
    name: "content-strategy",
    folder: "content-strategy",
    category: "content",
    description: "ジェットプロデュース（jet-produce.com）のブログコンテンツを中長期で計画・運用するための戦略スキル。ピラー・クラスター構造管理、編集カレンダー、KPI設計（3Tier）、季節テーマ、PDCAフロー。/content-strategy で起動。",
    command: null,
    lastModified: "2026-05-03T05:18:34",
    tags: []
  },
  {
    id: "daily-report",
    name: "daily-report",
    folder: "daily-report",
    category: "report",
    description: "【デイリーレポート作成時は必ずこのファイルを全文読んでから始めること】ファイル名はYYMMDDdaily-report.md、保存先はdaily-reports/、作成前にSTEP 0〜7を順守すること。スキルを読まずに独自フォーマットで作成することは絶対禁止。/daily-report で起動。",
    command: null,
    lastModified: "2026-05-05T21:19:53",
    tags: []
  },
  {
    id: "daily-report-quality-check",
    name: "daily-report-quality-check",
    folder: "daily-report-quality-check",
    category: "report",
    description: "デイリーレポート完成後に実行する品質チェックスキル。全セッション網羅・INCIDENT漏れ・クライアント名正確性・重要度順序を検証する。/daily-report-quality-check で起動。",
    command: null,
    lastModified: "2026-05-01T22:22:52",
    tags: []
  },
  {
    id: "form-automation",
    name: "📝 フォーム自動入力スキル",
    folder: "form-automation",
    category: "system",
    description: "PlaywrightベースのWebフォーム自動入力スキル。Google Sheetsから企業リストを読み込み、各社の問い合わせフォームに自動入力する（送信は人間が手動）。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-diagnostic",
    name: "GBP MEO診断レポート",
    folder: "gbp-diagnostic",
    category: "gbp-core",
    description: "GoogleマップURLを入力するだけで、見込み顧客のGBP（Googleビジネスプロフィール）を5軸×5段階で自動診断し、伸びしろTOP3・推定機会損失を含む営業用レポートを生成する。オーナーが「専門家に任せたい」と思える設計。",
    command: null,
    lastModified: "2026-05-03T08:05:45",
    tags: []
  },
  {
    id: "gbp-meo-beauty",
    name: "GBP MEO運用スキル｜美容室・エステ・ネイル",
    folder: "gbp-meo-beauty",
    category: "gbp-industry",
    description: "美容室・エステサロン・ネイルサロンに特化したGoogleビジネスプロフィールMEO運用スキル。ホットペッパービューティーとの棲み分け・スタイル写真の撮影戦略・スタイリスト別口コミ獲得・予約導線設計・美容師法の広告規制まで、美容業界固有のノウハウを体系化。コアスキル（gbp-meo-core）と併用する。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-meo-bodywork",
    name: "GBP MEO運用スキル｜施術院（整体院）",
    folder: "gbp-meo-bodywork",
    category: "gbp-industry",
    description: "施術院（整体院・整骨院・鍼灸院）に特化したGoogleビジネスプロフィールMEO運用スキル。整体/整骨/鍼灸のカテゴリ使い分け・資格差に基づく広告規制・施術写真の撮影テクニック・症状別キーワード戦略・あはき法対応まで、施術業界固有のノウハウを体系化。コアスキル（gbp-meo-core）と併用する。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-meo-core",
    name: "GBP MEO運用コアスキル",
    folder: "gbp-meo-core",
    category: "gbp-core",
    description: "Googleビジネスプロフィール（GBP）のMEO対策・ローカルSEO運用を、200社以上の支援実績を持つプロマーケターの視点で体系化したコアスキル。戦略立案→実行→効果測定→改善のPDCAを業種横断で実装する。",
    command: null,
    lastModified: "2026-05-01T22:43:43",
    tags: []
  },
  {
    id: "gbp-meo-education",
    name: "GBP MEO運用スキル｜教育（学習塾）",
    folder: "gbp-meo-education",
    category: "gbp-industry",
    description: "学習塾・予備校・スクールに特化したGoogleビジネスプロフィールMEO運用スキル。口コミ機能制限リスク回避・保護者/生徒の二層ターゲット戦略・合格実績の訴求方法・季節講習連動施策・カテゴリ設定の落とし穴まで、教育業界固有のノウハウを体系化。コアスキル（gbp-meo-core）と併用する。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-meo-legal",
    name: "GBP MEO運用スキル｜士業（税理士・司法書士）",
    folder: "gbp-meo-legal",
    category: "gbp-industry",
    description: "士業（税理士・司法書士フォーカス）に特化したGoogleビジネスプロフィールMEO運用スキル。YMYL/E-E-A-T最重要の専門家ブランディング・守秘義務と口コミの両立・専門特化キーワード戦略・法改正連動の投稿施策・高権威Schema実装まで、士業固有のノウハウを体系化。コアスキル（gbp-meo-core）と併用する。",
    command: null,
    lastModified: "2026-05-08T18:52:53",
    tags: []
  },
  {
    id: "gbp-meo-medical",
    name: "GBP MEO運用スキル｜クリニック（歯科）",
    folder: "gbp-meo-medical",
    category: "gbp-industry",
    description: "クリニック（歯科フォーカス）に特化したGoogleビジネスプロフィールMEO運用スキル。医療広告ガイドライン遵守・YMYL/E-E-A-T対応・患者口コミ獲得・診療科目別カテゴリ設定・Schema実装まで、医療機関固有のノウハウを体系化。コアスキル（gbp-meo-core）と併用する。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-meo-post-core",
    name: "GBP MEO長文投稿ライティングスキル",
    folder: "gbp-meo-post-core",
    category: "gbp-core",
    description: "Googleビジネスプロフィール（GBP）運用において、検索アルゴリズム（NLP）の関連性評価を最大化するための「本文1000文字＋固定フッター150〜200文字」型プロフェッショナル投稿ライティングスキル。",
    command: null,
    lastModified: "2026-05-08T18:13:35",
    tags: []
  },
  {
    id: "gbp-meo-post-dental-occlusion",
    name: "歯科クリニック向けGBP投稿スキル（特殊・噛み合わせ特化）",
    folder: "gbp-meo-post-dental-occlusion",
    category: "gbp-post",
    description: "ジェットプロデュースのクライアントワーク用。月を入力すると8つの季節テーマ案を提示し、選ばれた4記事を確実な医療広告ガイドライン準拠（慎重表現ルール等）のもと、1000文字規模で一括生成するハイエンドプロンプト。",
    command: null,
    lastModified: "2026-05-06T09:00:14",
    tags: []
  },
  {
    id: "gbp-meo-post-dental-preventive",
    name: "歯科クリニック向けGBP投稿スキル（一般・予防歯科特化）",
    folder: "gbp-meo-post-dental-preventive",
    category: "gbp-post",
    description: "ジェットプロデュースのクライアントワーク用。月を入力すると8つの季節テーマ案を提示し、選んだ4記事を「1000文字の本文＋オーナー報告用の目的文」のセットで一括生成するプロンプト。",
    command: null,
    lastModified: "2026-05-06T08:59:58",
    tags: []
  },
  {
    id: "gbp-meo-post-jetproduce",
    name: "ジェットプロデュース自社GBP投稿スキル",
    folder: "gbp-meo-post-jetproduce",
    category: "gbp-post",
    description: "ジェットプロデュース様自身のGoogleビジネスプロフィール（GBP）における集客・相談獲得を目的とした長文投稿作成スキル。「寄り添い型のパートナー」トーンでMEOあるある（30テーマ）の課題を提示し、ホームページからの問い合わせへ誘導する。",
    command: null,
    lastModified: "2026-05-07T10:16:44",
    tags: []
  },
  {
    id: "gbp-meo-real-estate",
    name: "GBP MEO運用スキル｜不動産",
    folder: "gbp-meo-real-estate",
    category: "gbp-industry",
    description: "不動産会社（賃貸仲介・売買仲介・管理会社）に特化したGoogleビジネスプロフィールMEO運用スキル。物件検索行動への対応・エリア別キーワード戦略・来店予約導線・宅建業法の広告規制・ポータルサイトとの棲み分けまで、不動産業界固有のノウハウを体系化。コアスキル（gbp-meo-core）と併用する。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-meo-restaurant",
    name: "GBP MEO運用スキル｜飲食店（居酒屋）",
    folder: "gbp-meo-restaurant",
    category: "gbp-industry",
    description: "飲食店（居酒屋フォーカス）に特化したGoogleビジネスプロフィールMEO運用スキル。メニュー戦略・予約連携・口コミ獲得・季節施策・GBP新機能活用まで、飲食業界固有のノウハウを体系化。コアスキル（gbp-meo-core）と併用する。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-meo-retail",
    name: "GBP MEO運用スキル｜小売・物販",
    folder: "gbp-meo-retail",
    category: "gbp-industry",
    description: "小売店・物販店舗（アパレル・雑貨・花屋・書店・食料品店等）に特化したGoogleビジネスプロフィールMEO運用スキル。商品写真戦略・EC連携・Googleショッピング連動・在庫情報活用・季節商戦連動施策まで、小売業界固有のノウハウを体系化。コアスキル（gbp-meo-core）と併用する。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-meo-service",
    name: "GBP MEO運用スキル｜工務店・リフォーム",
    folder: "gbp-meo-service",
    category: "gbp-industry",
    description: "工務店・リフォーム会社・住宅関連サービスに特化したGoogleビジネスプロフィールMEO運用スキル。施工事例の効果的な見せ方・エリア戦略・建設業法の広告規制・見積り相談への導線設計・ビフォーアフターの活用方法まで、建築業界固有のノウハウを体系化。コアスキル（gbp-meo-core）と併用する。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-monthly-report",
    name: "GBP月次レポート自動生成",
    folder: "gbp-monthly-report",
    category: "gbp-core",
    description: "クライアント向けGBP月次パフォーマンスレポートをNode.jsスクリプトで自動生成するスキル。Google SheetsのCSVデータを読み込み、KPI計算・競合比較・推奨アクションを含むHTML/PDFレポートを一括生成。スプレッドシート連携版（generate_report_from_sheet.js）とローカルCSV版（generate_monthly_report.js）の2モードを搭載。",
    command: null,
    lastModified: "2026-05-07T08:54:57",
    tags: []
  },
  {
    id: "gbp-partner-research",
    name: "GBPパートナー候補リサーチ コアスキル",
    folder: "gbp-partner-research",
    category: "research",
    description: "GBP/MEO運用サービスの協業パートナー候補となる業種をリサーチし、優先順位付けとキーワード設計を行うコアスキル。1000社超の集客支援実績を持つプロマーケターの視点で業種評価・キーワード設計を行い、company-searchスキルと連携して企業リスト抽出まで一気通貫で実行する。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "gbp-post-quality-check",
    name: "GBP投稿文 品質チェックスキル",
    folder: "gbp-post-quality-check",
    category: "gbp-core",
    description: "GBP投稿文（本文・タイトル・固定フッター）を報告前に品質検査するスキル。誇大表現・断言・誤解を招く表現・誤字の基本4軸＋医療広告ガイドライン・士業法規制の業種別コンプライアンス軸＋誤解を招く表現軸を含む全7軸でチェックし、「〇〇の観点でチェック完了」報告を出力してから出稿する。/gbp-post-quality-check で起動。",
    command: null,
    lastModified: "2026-05-28T04:34:27",
    tags: []
  },
  {
    id: "gbp-report-quality-check",
    name: "gbp-report-quality-check",
    folder: "gbp-report-quality-check",
    category: "gbp-core",
    description: "GBP月次レポートのHTML/PDF生成物が正しいかを機械的に検査・検証する。/gbp-report-quality-check で起動。",
    command: null,
    lastModified: "2026-05-02T06:24:24",
    tags: []
  },
  {
    id: "gbp-review-analysis",
    name: "gbp-review-analysis",
    folder: "gbp-review-analysis",
    category: "gbp-core",
    description: "GBP口コミデータの全件抽出・テキスト分析・強み/弱み抽出・HTMLレポート生成スキル。GoogleマップURLを入力→Playwrightで口コミ全件取得→テーマ分類・感情分析→営業用/伴走用レポート出力。/gbp-review-analysis で起動。",
    command: null,
    lastModified: "2026-05-04T05:31:28",
    tags: []
  },
  {
    id: "gbp-review-reply",
    name: "gbp-review-reply",
    folder: "gbp-review-reply",
    category: "gbp-core",
    description: "GBP口コミへの返信案を自動生成するスキル。星評価別×5トーンで複数案を出力。SEOキーワードを自然に含め、MEOランキング向上に貢献。/gbp-review-reply で起動。",
    command: null,
    lastModified: "2026-05-09T21:49:17",
    tags: []
  },
  {
    id: "git-backup",
    name: "Git バックアップスキル",
    folder: "git-backup",
    category: "system",
    description: "|",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "great-presenter",
    name: "🎤 グレートプレゼンタースキル v2.0",
    folder: "great-presenter",
    category: "web",
    description: "プロフェッショナル・スピーチ＆プレゼンテーション総合スキル。講話の企画・台本作成・レジュメ設計・演出ポイント・添削を支援する。倫理法人会モーニングセミナー40分講話にも完全対応。/great-presenter で起動。",
    command: null,
    lastModified: "2026-05-02T06:41:53",
    tags: []
  },
  {
    id: "idea-inbox",
    name: "💡 idea-inbox スキル",
    folder: "idea-inbox",
    category: "system",
    description: ">",
    command: null,
    lastModified: "2026-05-02T09:49:08",
    tags: []
  },
  {
    id: "ops-pdca",
    name: "ops-pdca",
    folder: "ops-pdca",
    category: "system",
    description: "contact-auto の日次運用PDCAサイクル。「送信→集計→分析→パッチ→検証→SKILL反映」の一気通貫フローを定義。daily-report の CHECK-1/CHECK-2 と contact-auto の学習エンジンを橋渡しする。/ops-pdca で起動。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "sales-copywriting",
    name: "sales-copywriting",
    folder: "sales-copywriting",
    category: "system",
    description: "お問い合わせフォーム経由のBtoB営業提案文を「型」で量産・PDCA改善するスキル。成約はゴールではなくスタート。伴走者としての最初の握手を設計する。/sales-copywriting で起動。",
    command: null,
    lastModified: "2026-05-05T07:51:15",
    tags: []
  },
  {
    id: "sales-copywriting-qa",
    name: "sales-copywriting-qa",
    folder: "sales-copywriting-qa",
    category: "system",
    description: "sales-copywritingスキルで作成した提案文の品質を辛口で検査するスキル。型通りか、漏れがないか、誤解を生むリスクはないかを多角的にフィードバックする。/sales-copywriting-qa で起動。",
    command: null,
    lastModified: "2026-05-05T07:55:09",
    tags: []
  },
  {
    id: "site-seo-launch",
    name: "site-seo-launch",
    folder: "site-seo-launch",
    category: "web",
    description: "WordPress/SWELLテーマで制作したサイトを本番公開する際のSEO設定スキル。SEO SIMPLE PACK設定・GA4連携（CV計測・内部除外含む）・Search Console登録・インデックスリクエスト・公開前後チェックリストを網羅。/site-seo-launch で起動。",
    command: null,
    lastModified: "2026-05-09T15:02:39",
    tags: []
  },
  {
    id: "skill-management",
    name: "skill-management",
    folder: "skill-management",
    category: "system",
    description: "スキルの作り方・保存場所・命名規則・更新ルールを定めたメタスキル。【最重要】あらゆるタスク実行前に「現在のスキル一覧」を確認し、該当スキルがあればそのSKILL.mdを読んでから作業を開始すること。/skill-management で起動。",
    command: null,
    lastModified: "2026-05-14T17:19:43",
    tags: []
  },
  {
    id: "small-company-research",
    name: "Small Company Research スキル",
    folder: "small-company-research",
    category: "research",
    description: "小規模企業の提案候補リストを作成するリサーチスキル。ポータルサイト・検索結果・比較記事から候補企業を収集し、公式サイトから企業情報を抽出、キーワード判定・重複管理・品質チェックを経てGoogle Sheets/CSVに出力する。スクレイピングファースト・トークン不使用設計。",
    command: null,
    lastModified: "2026-05-01T14:45:19",
    tags: []
  },
  {
    id: "survey-app-deploy",
    name: "survey-app-deploy",
    folder: "survey-app-deploy",
    category: "system",
    description: "|",
    command: null,
    lastModified: "2026-05-14T17:19:29",
    tags: []
  },
  {
    id: "website-production",
    name: "🏗️ ホームページ制作スキル — WordPress × SWELL 完全フロー",
    folder: "website-production",
    category: "web",
    description: "WordPressとSWELLテーマを使ったホームページ制作の完全フロー。企画→デザイン→構築→公開→SEOまでの全工程チェックリストと知見を集積。",
    command: null,
    lastModified: "2026-05-09T15:02:27",
    tags: []
  }
];

// categories.js — generated by generate-data.ps1 (ASCII-safe, no Japanese)
// Edit labels/icons here and re-run generate-data.ps1 to update dashboard

const CATEGORIES = [
  { id: "all",          label: "\u3059\u3079\u3066",           icon: "\u26a1",  color: "#a78bfa" },
  { id: "system",       label: "\u30b7\u30b9\u30c6\u30e0\u30fb\u30c4\u30fc\u30eb",  icon: "\uD83D\uDEE0\uFE0F",  color: "#60a5fa" },
  { id: "report",       label: "\u30ec\u30dd\u30fc\u30c8\u30fb\u65e5\u6b21",   icon: "\uD83D\uDCCB",  color: "#34d399" },
  { id: "content",      label: "SNS\u30fb\u30b3\u30f3\u30c6\u30f3\u30c4",  icon: "\uD83D\uDCF1",  color: "#f472b6" },
  { id: "web",          label: "Web\u5236\u4f5c\u30fb\u305d\u306e\u4ed6", icon: "\uD83C\uDF10",  color: "#fb923c" },
  { id: "research",     label: "\u30ea\u30b5\u30fc\u30c1",       icon: "\uD83D\uDD0D",  color: "#fbbf24" },
  { id: "gbp-core",     label: "GBP\u57fa\u76e4",          icon: "\uD83D\uDCCA",  color: "#4ade80" },
  { id: "gbp-post",     label: "GBP\u6295\u7a3f\u696d\u7a2e\u5225",   icon: "\u270D\uFE0F",  color: "#a78bfa" },
  { id: "gbp-industry", label: "GBP\u696d\u7a2e\u5225\u904b\u7528",   icon: "\uD83C\uDFEA",  color: "#38bdf8" },
];
